"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarDays, LockKeyhole, ShoppingBag, Sparkles } from "lucide-react";
import { useAccess } from "@/components/access/AccessShell";
import { supabase } from "@/lib/supabase/client";

type Memory={id:string;category:string;title:string;summary:string|null;details:Record<string,unknown>;products_used:unknown;maintenance_notes:string|null;approved_photo_urls:string[];created_at:string;updated_at:string;service_id:string|null;staff_id:string|null;appointment_id:string|null};
type FirstAppointment={start_at:string;service:{name:string}|null;staff:{name:string}|null};
type Photo={id:string;image_url:string;caption:string|null;photo_type:string;taken_at:string};
type ProductRecommendation={id:string;product_slug:string;reason:string|null};

const familyMeta:Record<string,{label:string;tagline:string}>={
  color:{label:"My Hair Color",tagline:"Color + formula"},blowdry:{label:"My Blowdry",tagline:"My signature finish"},cut:{label:"My Cut",tagline:"Shape + length"},treatment:{label:"My Treatments",tagline:"Hair health"},styling:{label:"My Styling",tagline:"Looks worth repeating"},extensions:{label:"My Extensions",tagline:"Length + color match"},nails:{label:"My Nails",tagline:"Shape + shade"},lashes:{label:"My Lashes",tagline:"Map + curl"},brows:{label:"My Brows",tagline:"Shape + tint"},makeup:{label:"My Makeup",tagline:"My best tones"},tanning:{label:"My Glow",tagline:"My perfect tone"},hair:{label:"My Hair",tagline:"Hair memory"},general:{label:"My Beauty",tagline:"Personal details"}
};

export default function BeautyProfilePage(){
  const {profile}=useAccess();const [memory,setMemory]=useState<Memory[]>([]);const [first,setFirst]=useState<FirstAppointment|null>(null);const [photos,setPhotos]=useState<Photo[]>([]);const [products,setProducts]=useState<ProductRecommendation[]>([]);const [loading,setLoading]=useState(true);
  useEffect(()=>{if(!profile)return;(async()=>{const queries:any[]=[
    supabase.from("client_memory").select("id,category,title,summary,details,products_used,maintenance_notes,approved_photo_urls,created_at,updated_at,service_id,staff_id,appointment_id").eq("client_id",profile.id).eq("client_visible",true).order("updated_at",{ascending:false}),
    supabase.from("appointments").select("start_at,service:service_id(name),staff:staff_id(name)").eq("client_id",profile.id).in("status",["confirmed","in_progress","completed"]).order("start_at",{ascending:true}).limit(1).maybeSingle(),
    supabase.from("client_photos").select("id,image_url,caption,photo_type,taken_at").eq("client_id",profile.id).eq("visibility","client_visible").order("taken_at",{ascending:false}),
  ];if(profile.product_recommendations_enabled)queries.push(supabase.from("client_product_recommendations").select("id,product_slug,reason").eq("client_id",profile.id).eq("client_visible",true).in("status",["approved","published","accepted"]).order("created_at",{ascending:false}).limit(8));const r=await Promise.all(queries);setMemory((r[0].data as Memory[])||[]);setFirst((r[1].data as FirstAppointment|null)||null);setPhotos((r[2].data as Photo[])||[]);if(profile.product_recommendations_enabled)setProducts((r[3]?.data as ProductRecommendation[])||[]);setLoading(false)})()},[profile?.id,profile?.product_recommendations_enabled]);
  const families=useMemo(()=>{const map=new Map<string,Memory[]>();memory.forEach(m=>{const family=String(m.details?.service_family||m.category||"general");if(!map.has(family))map.set(family,[]);map.get(family)!.push(m)});return [...map.entries()]},[memory]);
  if(!profile)return null;
  return <div className="pb-12">
    <section className="overflow-hidden rounded-[28px] bg-[#34261F] text-ivory shadow-[0_18px_50px_rgba(52,38,31,.12)]"><div className="p-6 md:p-9"><p className="text-[9px] uppercase tracking-[.28em] text-champagne">Gloria Access</p><h1 className="mt-2 font-serif text-[43px] md:text-[56px] leading-none">My Beauty Profile</h1><p className="mt-4 max-w-[620px] text-[13px] leading-relaxed text-ivory/65">Tu color, tus fórmulas, tus acabados, tus tonos y los pequeños detalles que hacen que tu próxima visita empiece donde terminó la anterior.</p></div><div className="border-t border-white/10 bg-white/[.04] px-6 py-4 md:px-9"><p className="font-serif italic text-[18px] text-champagne">Beauty that remembers you.</p></div></section>

    {loading?<p className="mt-8 text-[12px] text-taupe">Preparando tu Beauty Profile…</p>:profile.beauty_state==="no_appointment_history"?<Locked/>:memory.length===0?<Started first={first}/>:<>
      <section className="mt-7"><div className="flex items-end justify-between gap-4"><div><p className="text-[9px] uppercase tracking-[.22em] text-mocha">Your beauty memory</p><h2 className="mt-1 font-serif text-[36px] leading-none">Todo lo que ya sabemos que te gusta.</h2></div><span className="hidden sm:block text-[10px] text-taupe">{families.length} áreas guardadas</span></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{families.map(([family,items])=><BeautyCard key={family} family={family} items={items}/>)}</div></section>

      {photos.length>0&&<section className="mt-9"><p className="text-[9px] uppercase tracking-[.22em] text-mocha">My Looks</p><h2 className="mt-2 font-serif text-[34px]">Resultados que vale la pena recordar.</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{photos.slice(0,8).map(p=><figure key={p.id} className="overflow-hidden rounded-[20px] border border-champagne/25 bg-white/60"><div className="relative aspect-[4/5]"><Image src={p.image_url} alt={p.caption||"Gloria Beauty Salon result"} fill className="object-cover"/></div>{p.caption&&<figcaption className="p-3 text-[11px] text-taupe">{p.caption}</figcaption>}</figure>)}</div></section>}

      {(uniqueProducts(memory).length>0||products.length>0)&&<section className="mt-9 rounded-[26px] border border-champagne/30 bg-[#EFE4DC]/45 p-6 md:p-8"><div className="flex items-center gap-2 text-mocha"><ShoppingBag size={18}/><p className="text-[9px] uppercase tracking-[.2em]">My Routine</p></div><h2 className="mt-2 font-serif text-[35px] leading-none">Los productos que conocemos de tu cabello.</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{uniqueProducts(memory).map((p,i)=><div key={`${p.type}-${p.name}-${i}`} className="rounded-[17px] bg-white/70 p-4"><p className="text-[8px] uppercase tracking-[.16em] text-taupe">{human(p.type)}</p><p className="mt-1 font-serif text-[22px]">{p.name}</p></div>)}{products.map(p=><Link key={p.id} href={`/access/shop?product=${encodeURIComponent(p.product_slug)}`} className="rounded-[17px] bg-white/70 p-4"><p className="text-[8px] uppercase tracking-[.16em] text-mocha">Recommended for you</p><p className="mt-1 font-serif text-[22px]">{human(p.product_slug.replace(/^truss-/,""))}</p>{p.reason&&<p className="mt-2 text-[10px] text-taupe">{p.reason}</p>}</Link>)}</div></section>}
    </>}
  </div>
}

function BeautyCard({family,items}:{family:string;items:Memory[]}){const m=items[0];const details=Object.entries(m.details||{}).filter(([k,v])=>k!=="service_family"&&v!==null&&v!=="");const href=`/access/book${m.service_id?`?service=${encodeURIComponent(m.service_id)}${m.staff_id?`&staff=${encodeURIComponent(m.staff_id)}`:""}&memory=${encodeURIComponent(m.id)}`:""}`;return <article className="overflow-hidden rounded-[24px] border border-champagne/30 bg-white/75 shadow-[0_8px_30px_rgba(52,38,31,.04)]"><div className="bg-[#EFE4DC]/55 p-5"><p className="text-[8px] uppercase tracking-[.2em] text-mocha">{familyMeta[family]?.tagline||"Beauty memory"}</p><h3 className="mt-1 font-serif text-[32px] leading-none">{familyMeta[family]?.label||human(family)}</h3>{m.summary&&<p className="mt-3 text-[12px] leading-relaxed text-taupe">{m.summary}</p>}</div><div className="p-5"><dl className="grid grid-cols-2 gap-x-5 gap-y-4">{details.slice(0,10).map(([k,v])=><div key={k}><dt className="text-[8px] uppercase tracking-[.14em] text-taupe">{human(k)}</dt><dd className="mt-1 text-[12px] font-medium">{formatValue(v)}</dd></div>)}</dl>{m.maintenance_notes&&<div className="mt-5 rounded-[16px] bg-[#FBF8F3] p-4"><p className="text-[8px] uppercase tracking-[.16em] text-mocha">Next time</p><p className="mt-2 text-[11px] leading-relaxed text-taupe">{m.maintenance_notes}</p></div>}<Link href={href} className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#4A352B] px-4 py-2.5 text-[9px] uppercase tracking-[.12em] text-ivory">Book this again <ArrowRight size={14}/></Link></div></article>}
function Locked(){return <section className="mt-8 rounded-[26px] border border-champagne/30 bg-white/65 p-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full border border-champagne/45 text-mocha"><LockKeyhole size={20}/></div><h2 className="mt-5 font-serif text-[36px]">Your beauty profile starts here</h2><p className="mt-3 text-[12px] text-taupe">Después de tu primera visita, Gloria y el team podrán ir guardando tus preferencias reales.</p><Link href="/access/book" className="mt-6 inline-flex rounded-full bg-[#4A352B] px-5 py-3 text-[9px] uppercase tracking-[.13em] text-ivory">Reservar cita</Link></section>}
function Started({first}:{first:FirstAppointment|null}){return <section className="mt-8 rounded-[26px] border border-champagne/30 bg-white/65 p-7"><Sparkles size={19} className="text-mocha"/><p className="mt-4 text-[9px] uppercase tracking-[.2em] text-mocha">Your beauty journey has started</p><h2 className="mt-2 font-serif text-[36px]">Tu perfil se irá haciendo más tú con cada visita.</h2>{first&&<div className="mt-5 rounded-[18px] bg-[#FBF8F3] p-4"><p className="font-serif text-[23px]">{first.service?.name||"Appointment"}</p><p className="mt-1 text-[10px] text-taupe">{first.staff?.name||"Gloria Beauty Salon"} · {date(first.start_at)}</p></div>}</section>}
function uniqueProducts(memory:Memory[]){const out:{type:string;name:string}[]=[];const seen=new Set<string>();memory.forEach(m=>{if(Array.isArray(m.products_used))m.products_used.forEach((x:any)=>{const type=typeof x==="object"?String(x.type||"product"):"product";const name=typeof x==="object"?String(x.name||""):String(x||"");const key=`${type}|${name}`.toLowerCase();if(name&&!seen.has(key)){seen.add(key);out.push({type,name})}})});return out}
function human(v:string){return v.replaceAll("_"," ").replaceAll("-"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function formatValue(v:unknown){if(Array.isArray(v))return v.join(", ");if(v===null||v===undefined)return "—";return String(v)}
function date(v:string){return new Date(v).toLocaleDateString("es-US",{month:"long",day:"numeric",year:"numeric",timeZone:"America/New_York"})}
