"use client";

import { useEffect, useMemo, useState } from "react";
import { MessageCircle, Send } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Client={id:string;first_name:string;last_name:string;phone:string|null};
type Msg={id:string;client_id:string;sender_type:string;body:string;created_at:string;sender_staff_id:string|null};
type User={role:"owner"|"admin"|"staff";staff_id:string|null};

export default function MessagesPage(){
  const [clients,setClients]=useState<Client[]>([]);const [messages,setMessages]=useState<Msg[]>([]);const [user,setUser]=useState<User|null>(null);const [selected,setSelected]=useState<string|null>(null);const [body,setBody]=useState("");const [sending,setSending]=useState(false);const [error,setError]=useState<string|null>(null);
  async function load(){const {data:{session}}=await supabase.auth.getSession();if(!session)return;const [{data:u},{data:c},{data:m}]=await Promise.all([supabase.from("user_profiles").select("role,staff_id").eq("auth_user_id",session.user.id).eq("active",true).maybeSingle(),supabase.from("client_profiles").select("id,first_name,last_name,phone").order("first_name"),supabase.from("client_messages").select("id,client_id,sender_type,body,created_at,sender_staff_id").order("created_at")]);setUser((u as User|null)||null);setClients((c as Client[])||[]);setMessages((m as Msg[])||[]);if(!selected&&(c as Client[]|null)?.length)setSelected((c as Client[])[0].id)}
  useEffect(()=>{load()},[]);
  const thread=useMemo(()=>messages.filter(m=>m.client_id===selected),[messages,selected]);
  async function send(){if(!selected||!body.trim()||!user)return;setSending(true);setError(null);const sender_type=user.role==="staff"?"staff":"admin";const {error}=await supabase.from("client_messages").insert({client_id:selected,sender_type,sender_staff_id:user.staff_id,body:body.trim()});setSending(false);if(error){setError(error.message);return;}setBody("");await load()}
  const current=clients.find(c=>c.id===selected);
  return <div><p className="text-[10px] uppercase tracking-[0.28em] text-mocha">Gloria Hub</p><h1 className="mt-2 font-serif text-[48px] md:text-[58px] leading-none">Messages</h1><p className="mt-3 text-[13px] text-taupe">Simple client conversations tied to the same client profile. Automation emails stay separate.</p>
    <div className="mt-8 grid min-h-[580px] overflow-hidden rounded-[26px] border border-champagne/30 bg-white/40 md:grid-cols-[280px_1fr]"><aside className="border-b md:border-b-0 md:border-r border-champagne/25 p-3"><p className="px-3 py-2 text-[9px] uppercase tracking-[0.17em] text-taupe">Clients</p><div className="max-h-[220px] md:max-h-[520px] overflow-y-auto">{clients.length===0?<p className="px-3 py-4 text-[11px] text-taupe">No assigned clients yet.</p>:clients.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`w-full rounded-xl px-3 py-3 text-left ${selected===c.id?"bg-espresso text-ivory":"hover:bg-blush/25"}`}><p className="text-[12px] font-medium">{[c.first_name,c.last_name].filter(Boolean).join(" ")||"Client"}</p><p className={`mt-1 text-[10px] ${selected===c.id?"text-ivory/60":"text-taupe"}`}>{c.phone||"No phone"}</p></button>)}</div></aside><section className="flex min-h-[430px] flex-col">{current?<><header className="border-b border-champagne/25 p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-blush/60 text-mocha"><MessageCircle size={18}/></span><div><h2 className="font-serif text-[27px] leading-none">{[current.first_name,current.last_name].filter(Boolean).join(" ")}</h2><p className="mt-1 text-[10px] text-taupe">Client conversation</p></div></div></header><div className="flex-1 space-y-3 overflow-y-auto p-5">{thread.length===0?<div className="pt-14 text-center"><p className="font-serif text-[29px]">No messages yet.</p><p className="mt-2 text-[11px] text-taupe">Start a conversation only when needed.</p></div>:thread.map(m=><div key={m.id} className={`max-w-[78%] rounded-[18px] px-4 py-3 ${m.sender_type==="client"?"bg-blush/45":"ml-auto bg-espresso text-ivory"}`}><p className="text-[12px] leading-relaxed">{m.body}</p><p className={`mt-2 text-[9px] ${m.sender_type==="client"?"text-taupe":"text-ivory/55"}`}>{new Date(m.created_at).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/New_York"})}</p></div>)}</div><footer className="border-t border-champagne/25 p-4"><div className="flex gap-2"><textarea value={body} onChange={e=>setBody(e.target.value)} rows={2} placeholder="Write a message..." className="min-h-[50px] flex-1 resize-none rounded-xl border border-taupe/25 bg-ivory/70 px-3 py-3 text-[12px] outline-none"/><button disabled={sending||!body.trim()} onClick={send} className="self-end rounded-full bg-espresso p-3 text-ivory disabled:opacity-40" aria-label="Send message"><Send size={17}/></button></div>{error&&<p className="mt-2 text-[10px] text-red-700">{error}</p>}</footer></>:<div className="flex flex-1 items-center justify-center p-8 text-center"><p className="text-[12px] text-taupe">Choose a client to open the conversation.</p></div>}</section></div>
  </div>
}
