"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Check, ChevronLeft, Save } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Appointment={id:string;client_name:string;status:string;start_at:string;service_id:string;staff_id:string;client_id:string;service:{name:string;category:string}|null;staff:{name:string}|null};
type Field={key:string;label:string;placeholder:string};
const fields:Record<string,Field[]>={
  hair:[{key:"tone",label:"Tono / Color",placeholder:"Beige miel / Neutro"},{key:"formula",label:"Fórmula",placeholder:"Fórmula de color / tonalizante / oxidante"},{key:"technique",label:"Técnica",placeholder:"Balayage, mechas, color de raíz..."},{key:"cut",label:"Corte / Largo",placeholder:"Capas, largo, enmarcado de rostro..."},{key:"style",label:"Acabado / Estilo",placeholder:"Ondas suaves, volumen en la raíz..."}],
  nails:[{key:"shade",label:"Color / Tono",placeholder:"OPI Bubble Bath"},{key:"shape",label:"Forma",placeholder:"Almendra corta"},{key:"service_type",label:"Tipo",placeholder:"Gel, DIP, Aprés, acrílico..."},{key:"design",label:"Diseño / Acabado",placeholder:"Natural, cromado, francesa..."}],
  brows:[{key:"shape",label:"Forma",placeholder:"Arco suave"},{key:"thickness",label:"Grosor",placeholder:"Natural / definido"},{key:"tone",label:"Tono de Henna",placeholder:"Si aplica"}],
  lashes:[{key:"style",label:"Estilo",placeholder:"Híbrido"},{key:"effect",label:"Efecto",placeholder:"Ojo de gato / Natural"},{key:"curl",label:"Curvatura",placeholder:"Curva C"},{key:"length",label:"Largo",placeholder:"Largos / mapeo"}],
  tanning:[{key:"type",label:"Tipo",placeholder:"Express / Regular"},{key:"tone",label:"Tono",placeholder:"Medio / Natural"},{key:"intensity",label:"Intensidad",placeholder:"Claro / Medio / Oscuro"},{key:"development",label:"Tiempo de desarrollo",placeholder:"Tiempo de enjuague recomendado"}],
  makeup:[{key:"foundation",label:"Base / Tono",placeholder:"Tono + subtono"},{key:"finish",label:"Acabado",placeholder:"Natural / soft glam / full glam"},{key:"eyes",label:"Ojos",placeholder:"Look de ojos"},{key:"lips",label:"Tono de labios",placeholder:"Nude / rosa / rojo..."}],
};
const categoryLabels:Record<string,string>={hair:"cabello",nails:"uñas",brows:"cejas",lashes:"pestañas",tanning:"bronceado",makeup:"maquillaje",general:"general"};

export default function CompleteVisitPage(){
  const params=useParams<{id:string}>();const router=useRouter();const [appt,setAppt]=useState<Appointment|null>(null);const [loading,setLoading]=useState(true);const [values,setValues]=useState<Record<string,string>>({});const [summary,setSummary]=useState("");const [maintenance,setMaintenance]=useState("");const [products,setProducts]=useState("");const [visible,setVisible]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState<string|null>(null);const [done,setDone]=useState(false);
  useEffect(()=>{(async()=>{const {data}=await supabase.from("appointments").select("id,client_name,status,start_at,service_id,staff_id,client_id,service:service_id(name,category),staff:staff_id(name)").eq("id",params.id).maybeSingle();setAppt((data as Appointment|null)||null);setLoading(false)})()},[params.id]);
  const category=appt?.service?.category||"general";const formFields=useMemo(()=>fields[category]||[{key:"details",label:"Detalles del servicio",placeholder:"¿Qué deberíamos recordar?"}],[category]);
  async function save(){if(!appt)return;setSaving(true);setMessage(null);const details=Object.fromEntries(Object.entries(values).filter(([,v])=>v.trim()).map(([k,v])=>[k,v.trim()]));const productList=products.split(",").map(x=>x.trim()).filter(Boolean);const title=buildTitle(category,details,appt.service?.name||"Visita");const {error}=await supabase.rpc("save_and_complete_appointment",{p_appointment_id:appt.id,p_title:title,p_summary:summary||null,p_details:details,p_client_visible:visible,p_maintenance_notes:maintenance||null,p_products_used:productList});setSaving(false);if(error){setMessage(error.message);return;}setDone(true)}
  if(loading)return <p className="text-[12px] text-taupe">Cargando visita...</p>;if(!appt)return <div><h1 className="font-serif text-[40px]">Cita no disponible.</h1><p className="mt-3 text-[12px] text-taupe">Puede que no tengas permiso para acceder a esta cita.</p></div>;
  if(done)return <div className="max-w-[620px] py-8 text-center"><div className="mx-auto h-14 w-14 rounded-full bg-espresso text-ivory flex items-center justify-center"><Check size={24}/></div><h1 className="mt-6 font-serif text-[44px] leading-none">Visita guardada.</h1><p className="mt-4 text-[13px] text-taupe">La cita quedó completada y se actualizó la memoria de la clienta.</p><button onClick={()=>router.push("/hub/my-agenda")} className="mt-7 rounded-full bg-espresso px-6 py-3 text-[9px] uppercase tracking-[0.14em] text-ivory">Volver a Mi Agenda</button></div>;
  return <div className="max-w-[850px]"><button onClick={()=>router.back()} className="inline-flex items-center gap-1 text-[11px] text-taupe"><ChevronLeft size={14}/>Volver</button><p className="mt-6 text-[10px] uppercase tracking-[0.26em] text-mocha">Actualizar memoria de la clienta</p><h1 className="mt-2 font-serif text-[46px] md:text-[56px] leading-none">Guardar y Completar</h1><p className="mt-3 text-[13px] text-taupe">{appt.client_name} · {appt.service?.name} · {appt.staff?.name}</p>
    <section className="mt-8 rounded-[28px] border border-champagne/30 bg-white/45 p-6 md:p-8"><div className="flex items-center justify-between gap-4"><div><p className="text-[9px] uppercase tracking-[0.18em] text-mocha">Memoria de {categoryLabels[category]||category}</p><h2 className="mt-2 font-serif text-[32px]">Guarda solo lo que importa para la próxima visita.</h2></div><label className="flex items-center gap-2 text-[11px] text-taupe"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/> Visible en Access</label></div><div className="mt-6 grid gap-4 md:grid-cols-2">{formFields.map(f=><FieldInput key={f.key} field={f} value={values[f.key]||""} onChange={v=>setValues(x=>({...x,[f.key]:v}))}/>)}</div><div className="mt-5 grid gap-4"><Text label="Resumen para la clienta" value={summary} onChange={setSummary} placeholder="Ejemplo: Balayage miel neutro con mechones suaves enmarcando el rostro."/><Text label="Recomendación de mantenimiento" value={maintenance} onChange={setMaintenance} placeholder="¿Qué debería recordar la clienta o el equipo para el mantenimiento?"/><FieldInput field={{key:"products",label:"Productos usados",placeholder:"Separados por coma: Net Mask, Frizz Zero..."}} value={products} onChange={setProducts}/></div>{message&&<p className="mt-4 text-[12px] text-red-700">{message}</p>}<button disabled={saving} onClick={save} className="mt-7 inline-flex items-center gap-2 rounded-full bg-espresso px-6 py-3 text-[10px] uppercase tracking-[0.14em] text-ivory disabled:opacity-50"><Save size={15}/>{saving?"Guardando...":"Guardar y Completar"}</button></section>
  </div>
}
function FieldInput({field,value,onChange}:{field:Field;value:string;onChange:(v:string)=>void}){return <label><span className="block text-[9px] uppercase tracking-[0.14em] text-taupe">{field.label}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={field.placeholder} className="mt-2 w-full rounded-xl border border-taupe/25 bg-ivory/70 px-3 py-3 text-[12px] outline-none"/></label>}
function Text({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <label><span className="block text-[9px] uppercase tracking-[0.14em] text-taupe">{label}</span><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-taupe/25 bg-ivory/70 px-3 py-3 text-[12px] outline-none"/></label>}
function buildTitle(category:string,d:Record<string,string>,fallback:string){if(category==="hair")return d.tone||d.technique||fallback;if(category==="nails")return [d.shade,d.shape].filter(Boolean).join(" · ")||fallback;if(category==="lashes")return [d.style,d.effect].filter(Boolean).join(" · ")||fallback;if(category==="tanning")return [d.type,d.tone].filter(Boolean).join(" · ")||fallback;return Object.values(d)[0]||fallback}
