"use client";

import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Settings={cancellation_window_hours:number;rescheduling_window_hours:number;booking_lead_minutes:number;booking_horizon_days:number;default_buffer_minutes:number;allow_same_day_booking:boolean;require_admin_approval:boolean;no_show_policy_text:string|null;cancellation_policy_text:string|null};

export default function AppointmentSettingsPage(){
  const [form,setForm]=useState<Settings|null>(null); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
  useEffect(()=>{(async()=>{const {data}=await supabase.from("appointment_settings").select("cancellation_window_hours,rescheduling_window_hours,booking_lead_minutes,booking_horizon_days,default_buffer_minutes,allow_same_day_booking,require_admin_approval,no_show_policy_text,cancellation_policy_text").eq("id",true).maybeSingle();setForm((data as Settings|null)||null)})()},[]);
  async function save(){if(!form)return;setSaving(true);setMessage(null);const {error}=await supabase.rpc("hub_update_appointment_settings",{p_cancellation_window_hours:form.cancellation_window_hours,p_rescheduling_window_hours:form.rescheduling_window_hours,p_booking_lead_minutes:form.booking_lead_minutes,p_booking_horizon_days:form.booking_horizon_days,p_default_buffer_minutes:form.default_buffer_minutes,p_allow_same_day_booking:form.allow_same_day_booking,p_require_admin_approval:form.require_admin_approval,p_no_show_policy_text:form.no_show_policy_text||"",p_cancellation_policy_text:form.cancellation_policy_text||""});setSaving(false);setMessage(error?error.message:"Guardado.")}
  if(!form)return <p className="text-sm text-taupe">Cargando configuración...</p>;
  return <div className="max-w-[900px]"><p className="text-[10px] uppercase tracking-[0.28em] text-mocha">Gloria Hub · Configuración</p><h1 className="mt-2 font-serif text-[46px] md:text-[58px] leading-none">Citas</h1><p className="mt-3 text-[13px] text-taupe">Controla ventanas de reserva, tiempos de espera y políticas, sin tener que tocar código.</p>
    <section className="mt-8 grid gap-4 md:grid-cols-2"><NumberField label="Ventana de cancelación (horas)" value={form.cancellation_window_hours} onChange={v=>setForm({...form,cancellation_window_hours:v})}/><NumberField label="Ventana de reprogramación (horas)" value={form.rescheduling_window_hours} onChange={v=>setForm({...form,rescheduling_window_hours:v})}/><NumberField label="Anticipación mínima para reservar (minutos)" value={form.booking_lead_minutes} onChange={v=>setForm({...form,booking_lead_minutes:v})}/><NumberField label="Horizonte de reserva (días)" value={form.booking_horizon_days} onChange={v=>setForm({...form,booking_horizon_days:v})}/><NumberField label="Buffer por defecto (minutos)" value={form.default_buffer_minutes} onChange={v=>setForm({...form,default_buffer_minutes:v})}/><Toggle label="Permitir reservar el mismo día" checked={form.allow_same_day_booking} onChange={v=>setForm({...form,allow_same_day_booking:v})}/><Toggle label="Requiere aprobación de un admin" checked={form.require_admin_approval} onChange={v=>setForm({...form,require_admin_approval:v})}/></section>
    <section className="mt-6 grid gap-4"><TextArea label="Política de cancelación" value={form.cancellation_policy_text||""} onChange={v=>setForm({...form,cancellation_policy_text:v})}/><TextArea label="Política de no-show" value={form.no_show_policy_text||""} onChange={v=>setForm({...form,no_show_policy_text:v})}/></section>
    {message&&<p className="mt-4 text-[12px] text-mocha">{message}</p>}<button onClick={save} disabled={saving} className="mt-6 inline-flex items-center gap-2 rounded-full bg-espresso px-6 py-3 text-[10px] uppercase tracking-[0.14em] text-ivory disabled:opacity-50"><Save size={15}/>{saving?"Guardando...":"Guardar configuración"}</button></div>
}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="rounded-[20px] border border-champagne/30 bg-white/40 p-5"><span className="text-[9px] uppercase tracking-[0.15em] text-taupe">{label}</span><input type="number" min={0} value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-3 w-full rounded-xl border border-taupe/25 bg-ivory px-3 py-3 text-[13px]"/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="rounded-[20px] border border-champagne/30 bg-white/40 p-5 flex items-center justify-between gap-4"><span className="text-[12px]">{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-5 w-5"/></label>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="rounded-[20px] border border-champagne/30 bg-white/40 p-5"><span className="text-[9px] uppercase tracking-[0.15em] text-taupe">{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} className="mt-3 w-full rounded-xl border border-taupe/25 bg-ivory px-3 py-3 text-[13px]"/></label>}
