"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Search } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Client={id:string;first_name:string;last_name:string;email:string|null;phone:string|null;access_status:string;beauty_state:string;created_at:string};
const accessLabels:Record<string,string>={invited:"Invitada",active:"Activa",inactive:"Inactiva",disabled:"Deshabilitada"};
const beautyLabels:Record<string,string>={no_appointment_history:"Sin historial de citas",appointment_confirmed:"Cita confirmada",beauty_profile_active:"Perfil de belleza activo"};

export default function HubClients(){
  const [clients,setClients]=useState<Client[]>([]); const [q,setQ]=useState(""); const [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{const {data}=await supabase.from("client_profiles").select("id,first_name,last_name,email,phone,access_status,beauty_state,created_at").order("updated_at",{ascending:false});setClients((data as Client[])||[]);setLoading(false)})()},[]);
  const filtered=useMemo(()=>clients.filter(c=>`${c.first_name} ${c.last_name} ${c.email||""} ${c.phone||""}`.toLowerCase().includes(q.toLowerCase())),[clients,q]);
  return <div><div className="flex flex-col md:flex-row md:items-end md:justify-between gap-5"><div><p className="text-[9px] uppercase tracking-[0.28em] text-mocha">Gloria Hub</p><h1 className="mt-2 font-serif text-[44px] md:text-[56px] leading-none">Clientas</h1><p className="mt-3 text-[13px] text-taupe">Un solo perfil por clienta. Citas, memoria e inteligencia, todo junto.</p></div><label className="flex items-center gap-2 rounded-full border border-champagne/35 bg-white/45 px-4 py-3 md:w-[320px]"><Search size={17} className="text-mocha"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar clientas" className="w-full bg-transparent text-[12px] outline-none placeholder:text-taupe/70"/></label></div>{loading?<p className="mt-8 text-[12px] text-taupe">Cargando clientas…</p>:filtered.length===0?<div className="mt-8 rounded-[26px] border border-champagne/30 bg-white/45 p-8"><p className="font-serif text-[28px]">No se encontraron clientas.</p></div>:<div className="mt-8 overflow-hidden rounded-[24px] border border-champagne/30 bg-white/40"><div className="hidden md:grid grid-cols-[1.2fr_1fr_.8fr_.8fr] gap-4 border-b border-champagne/25 px-5 py-3 text-[8px] uppercase tracking-[0.18em] text-taupe"><span>Clienta</span><span>Contacto</span><span>Acceso</span><span>Perfil de Belleza</span></div>{filtered.map(c=><Link href={`/hub/clients/${c.id}`} key={c.id} className="grid md:grid-cols-[1.2fr_1fr_.8fr_.8fr] gap-2 md:gap-4 border-b last:border-0 border-champagne/20 px-5 py-5 hover:bg-white/60"><div><p className="font-serif text-[24px] leading-none">{c.first_name||"Clienta"} {c.last_name}</p><p className="mt-1 text-[10px] text-taupe">Desde {new Date(c.created_at).toLocaleDateString("es-US",{month:"short",year:"numeric"})}</p></div><div className="text-[11px] text-taupe"><p>{c.email||"Sin email"}</p><p className="mt-1">{c.phone||"Sin teléfono"}</p></div><div><span className="inline-flex rounded-full bg-blush px-3 py-1.5 text-[8px] uppercase tracking-[0.12em] text-mocha">{accessLabels[c.access_status]||c.access_status}</span></div><div><span className="text-[10px] text-taupe">{beautyLabels[c.beauty_state]||c.beauty_state}</span></div></Link>)}</div>}</div>
}
