"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Check } from "lucide-react";
import { supabase } from "@/lib/supabase/client";
import { useAccess } from "@/components/access/AccessShell";

type Appt={id:string;service_id:string;staff_id:string;start_at:string;service:{name:string;duration_minutes:number}|null;staff:{name:string}|null};
type Staff={id:string;name:string};

export default function ReschedulePage(){
  const {profile}=useAccess(); const params=useParams<{id:string}>(); const router=useRouter();
  const [appt,setAppt]=useState<Appt|null>(null); const [staff,setStaff]=useState<Staff[]>([]); const [staffId,setStaffId]=useState(""); const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10)); const [slots,setSlots]=useState<string[]>([]); const [slot,setSlot]=useState(""); const [busy,setBusy]=useState(true); const [message,setMessage]=useState<string|null>(null); const [done,setDone]=useState(false);
  useEffect(()=>{if(!profile)return;(async()=>{const {data:a}=await supabase.from("appointments").select("id,service_id,staff_id,start_at,service:service_id(name,duration_minutes),staff:staff_id(name)").eq("id",params.id).eq("client_id",profile.id).maybeSingle();const item=(a as Appt|null)||null;setAppt(item);if(item){setStaffId(item.staff_id);setDate(new Date(item.start_at).toLocaleDateString("en-CA",{timeZone:"America/New_York"}));const {data:ss}=await supabase.from("staff_services").select("staff:staff_id(id,name)").eq("service_id",item.service_id);setStaff(((ss as any[])||[]).map(x=>x.staff).filter(Boolean));}setBusy(false)})()},[profile?.id,params.id]);
  useEffect(()=>{if(!appt||!staffId||!date)return;setBusy(true);setSlots([]);setSlot("");(async()=>{const {data}=await supabase.rpc("get_available_slots",{p_staff_id:staffId,p_service_id:appt.service_id,p_date:date});setSlots(((data||[]) as {slot_start:string}[]).map(x=>x.slot_start));setBusy(false)})()},[appt?.id,staffId,date]);
  async function confirm(){if(!appt||!slot)return;setBusy(true);setMessage(null);const {error}=await supabase.rpc("reschedule_my_appointment",{p_appointment_id:appt.id,p_new_staff_id:staffId,p_new_start_at:slot});setBusy(false);if(error){setMessage(error.message);return;}setDone(true)}
  if(done)return <div className="max-w-[620px] mx-auto text-center py-14"><div className="mx-auto h-14 w-14 rounded-full bg-espresso text-ivory flex items-center justify-center"><Check size={25}/></div><h1 className="mt-6 font-serif text-[44px] leading-none">Tu cita fue reprogramada ✨</h1><button onClick={()=>router.push(`/access/appointments/${params.id}`)} className="mt-7 rounded-full bg-espresso px-6 py-3 text-[9px] uppercase tracking-[0.14em] text-ivory">View appointment</button></div>;
  if(!appt&&!busy)return <p className="text-sm text-taupe">Appointment not found.</p>;
  return <div className="max-w-[700px]"><p className="text-[10px] uppercase tracking-[0.28em] text-mocha">Gloria Access</p><h1 className="mt-2 font-serif text-[44px] md:text-[54px] leading-none">Reprogramar</h1><p className="mt-3 text-[13px] text-taupe">Conservamos tu servicio. Puedes mantener o cambiar de profesional.</p>{appt&&<section className="mt-8 rounded-[28px] border border-champagne/30 bg-white/45 p-7"><p className="text-[9px] uppercase tracking-[0.16em] text-mocha">Current service</p><h2 className="mt-2 font-serif text-[32px]">{appt.service?.name}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="text-[9px] uppercase tracking-[0.15em] text-taupe">Professional</span><select value={staffId} onChange={e=>setStaffId(e.target.value)} className="mt-2 w-full rounded-xl border border-taupe/25 bg-ivory px-3 py-3 text-[12px]">{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span className="text-[9px] uppercase tracking-[0.15em] text-taupe">Date</span><input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)} className="mt-2 w-full rounded-xl border border-taupe/25 bg-ivory px-3 py-3 text-[12px]"/></label></div><div className="mt-6"><p className="text-[9px] uppercase tracking-[0.15em] text-taupe">Available times</p>{busy?<p className="mt-3 text-[12px] text-taupe">Loading...</p>:slots.length===0?<p className="mt-3 text-[12px] text-taupe">No availability for this date.</p>:<div className="mt-3 grid grid-cols-3 md:grid-cols-4 gap-2">{slots.map(s=><button key={s} onClick={()=>setSlot(s)} className={`rounded-xl border py-3 text-[12px] ${slot===s?"border-espresso bg-espresso text-ivory":"border-champagne/30 bg-white/50"}`}>{new Date(s).toLocaleTimeString("es-US",{hour:"numeric",minute:"2-digit",timeZone:"America/New_York"})}</button>)}</div>}</div>{message&&<p className="mt-4 text-[12px] text-red-700">{message}</p>}<button disabled={!slot||busy} onClick={confirm} className="mt-7 rounded-full bg-espresso px-6 py-3 text-[9px] uppercase tracking-[0.14em] text-ivory disabled:opacity-40">Confirm reschedule</button></section>}</div>
}
