"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { Check, Plus, Sparkles } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Client={id:string;first_name:string;last_name:string;email:string|null;phone:string|null;access_status:string;beauty_state:string;created_at:string;client_type:string};
type Memory={id:string;category:string;title:string;summary:string|null;details:Record<string,unknown>;client_visible:boolean;visibility:string;updated_at:string};
type Recommendation={id:string;type:string;category:string;title:string;description:string|null;reason:string|null;status:string;client_visible:boolean};
type Metrics={segment:string;lifetime_spend:number;average_ticket:number;completed_visits:number;last_visit:string|null;days_since_last_visit:number|null};
const categories=["hair","nails","brows","lashes","tanning","makeup"];
const categoryLabels:Record<string,string>={hair:"cabello",nails:"uñas",brows:"cejas",lashes:"pestañas",tanning:"bronceado",makeup:"maquillaje"};
const tabs=["overview","appointments","client_memory","products","orders","beauty_intelligence","activity"] as const;
const tabLabels:Record<string,string>={overview:"Resumen",appointments:"Citas",client_memory:"Memoria de la clienta",products:"Productos",orders:"Pedidos",beauty_intelligence:"Inteligencia de Belleza",activity:"Actividad"};
const accessLabels:Record<string,string>={invited:"Invitada",active:"Activa",inactive:"Inactiva",disabled:"Deshabilitada"};
const beautyLabels:Record<string,string>={no_appointment_history:"Sin historial",appointment_confirmed:"Cita confirmada",beauty_profile_active:"Perfil activo"};
const segmentLabels:Record<string,string>={new:"Nueva",regular:"Regular",loyal:"Fiel",vip:"VIP","at_risk":"En riesgo"};
const statusLabels:Record<string,string>={suggested:"Sugerida",approved:"Aprobada",published:"Publicada",dismissed:"Descartada",accepted:"Aceptada",expired:"Expirada"};
const clientTypeLabels:Record<string,string>={regular:"Clienta regular",ambassador:"Ambassador (intercambio)"};

export default function HubClientDetail(){
  const params=useParams<{id:string}>(); const id=params.id;
  const [client,setClient]=useState<Client|null>(null); const [memory,setMemory]=useState<Memory[]>([]); const [recs,setRecs]=useState<Recommendation[]>([]); const [metrics,setMetrics]=useState<Metrics|null>(null); const [tab,setTab]=useState<typeof tabs[number]>("overview"); const [open,setOpen]=useState(false); const [form,setForm]=useState({category:"hair",title:"",summary:"",visibility:"internal"});
  async function load(){const [{data:c},{data:m},{data:r},{data:v}]=await Promise.all([supabase.from("client_profiles").select("id,first_name,last_name,email,phone,access_status,beauty_state,created_at,client_type").eq("id",id).single(),supabase.from("client_memory").select("id,category,title,summary,details,client_visible,visibility,updated_at").eq("client_id",id).order("updated_at",{ascending:false}),supabase.from("beauty_recommendations").select("id,type,category,title,description,reason,status,client_visible").eq("client_id",id).order("created_at",{ascending:false}),supabase.from("client_value_metrics").select("segment,lifetime_spend,average_ticket,completed_visits,last_visit,days_since_last_visit").eq("client_id",id).maybeSingle()]);setClient(c as Client);setMemory((m as Memory[])||[]);setRecs((r as Recommendation[])||[]);setMetrics((v as Metrics|null)||null)}
  useEffect(()=>{if(id)load()},[id]);
  const grouped=useMemo(()=>categories.map(category=>[category,memory.filter(m=>m.category===category)] as const),[memory]);
  async function addMemory(e:FormEvent){e.preventDefault();const visible=form.visibility==="client_visible";const {error}=await supabase.from("client_memory").insert({client_id:id,category:form.category,title:form.title,summary:form.summary||null,details:{},client_visible:visible,visibility:form.visibility});if(!error){setOpen(false);setForm({category:"hair",title:"",summary:"",visibility:"internal"});load()}}
  async function publishRecommendation(rec:Recommendation){await supabase.from("beauty_recommendations").update({status:"published",client_visible:true}).eq("id",rec.id);load()}
  async function dismissRecommendation(rec:Recommendation){await supabase.from("beauty_recommendations").update({status:"dismissed",client_visible:false}).eq("id",rec.id);load()}
  async function toggleClientType(){if(!client)return;const next=client.client_type==="ambassador"?"regular":"ambassador";const {error}=await supabase.rpc("hub_update_client_type",{p_client_id:client.id,p_client_type:next});if(!error)load()}
  if(!client)return <p className="text-[12px] text-taupe">Cargando clienta…</p>;
  return <div><div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6"><div><p className="text-[9px] uppercase tracking-[0.28em] text-mocha">Perfil de clienta</p><h1 className="mt-2 font-serif text-[45px] md:text-[58px] leading-none">{client.first_name} {client.last_name}</h1><p className="mt-3 text-[12px] text-taupe">{client.email||"Sin email"} · {client.phone||"Sin teléfono"}</p></div><div className="flex flex-wrap gap-2"><Badge>{accessLabels[client.access_status]||client.access_status}</Badge><Badge>{beautyLabels[client.beauty_state]||client.beauty_state}</Badge>{metrics&&<Badge>{segmentLabels[metrics.segment]||metrics.segment}</Badge>}{client.client_type==="ambassador"&&<span className="rounded-full bg-espresso px-3 py-1.5 text-[8px] uppercase tracking-[0.12em] text-champagne">Ambassador</span>}<button onClick={toggleClientType} className="rounded-full border border-mocha/30 px-3 py-1.5 text-[8px] uppercase tracking-[0.12em] text-mocha">{client.client_type==="ambassador"?"Quitar Ambassador":"Marcar Ambassador"}</button></div></div>
  <p className="mt-3 text-[11px] text-taupe">{clientTypeLabels[client.client_type]||client.client_type} — las citas de Ambassadors nunca cuentan como ingreso real, aunque el servicio tenga un precio de lista.</p></div>
  <div className="mt-8 overflow-x-auto border-b border-champagne/25"><div className="flex min-w-max gap-6">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`pb-3 text-[9px] uppercase tracking-[0.17em] ${tab===t?"border-b border-mocha text-mocha":"text-taupe"}`}>{tabLabels[t]}</button>)}</div></div>
  {tab==="overview"&&<div className="mt-7 grid gap-4 md:grid-cols-4"><Stat label="Segmento de clienta" value={metrics?segmentLabels[metrics.segment]||metrics.segment:"No calculado"}/><Stat label="Visitas completadas" value={String(metrics?.completed_visits||0)}/><Stat label="Ticket promedio" value={metrics?`$${Number(metrics.average_ticket||0).toFixed(0)}`:"—"}/><Stat label="Última visita" value={metrics?.last_visit?new Date(metrics.last_visit).toLocaleDateString("es-US"):"—"}/></div>}
  {tab==="client_memory"&&<section className="mt-7"><div className="flex items-center justify-between gap-4"><div><p className="text-[9px] uppercase tracking-[0.22em] text-mocha">Memoria de la clienta</p><h2 className="mt-2 font-serif text-[35px] leading-none">Recuerda a la clienta, no solo la cita.</h2></div><button onClick={()=>setOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-full bg-espresso px-5 py-3 text-[9px] uppercase tracking-[0.14em] text-ivory"><Plus size={15}/>Agregar memoria</button></div>{open&&<form onSubmit={addMemory} className="mt-5 rounded-[24px] border border-champagne/30 bg-white/45 p-5 grid gap-4 md:grid-cols-4"><Select value={form.category} onChange={v=>setForm(f=>({...f,category:v}))} options={categories}/><input required value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="Título de la memoria" className="rounded-xl border border-taupe/25 bg-ivory/70 px-4 py-3 text-[12px] outline-none"/><input value={form.summary} onChange={e=>setForm(f=>({...f,summary:e.target.value}))} placeholder="Resumen breve" className="rounded-xl border border-taupe/25 bg-ivory/70 px-4 py-3 text-[12px] outline-none"/><select value={form.visibility} onChange={e=>setForm(f=>({...f,visibility:e.target.value}))} className="rounded-xl border border-taupe/25 bg-ivory/70 px-4 py-3 text-[12px]"><option value="internal">Solo interno</option><option value="client_visible">Visible en Access</option></select><button className="md:col-span-4 justify-self-start rounded-full bg-mocha px-5 py-3 text-[9px] uppercase tracking-[0.14em] text-ivory">Guardar memoria</button></form>}<div className="mt-6 space-y-7">{grouped.map(([category,items])=><div key={category}><div className="flex items-center gap-3"><p className="text-[9px] uppercase tracking-[0.22em] text-mocha">Memoria de {categoryLabels[category]||category}</p><span className="h-px flex-1 bg-champagne/25"/></div>{items.length===0?<p className="mt-3 text-[12px] text-taupe">Todavía no hay memoria de {categoryLabels[category]||category}.</p>:<div className="mt-3 grid gap-3 md:grid-cols-2">{items.map(m=><article key={m.id} className="rounded-[22px] border border-champagne/30 bg-white/45 p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-serif text-[27px] leading-none">{m.title}</h3><span className={`rounded-full px-2.5 py-1 text-[8px] uppercase tracking-[.1em] ${m.client_visible?"bg-blush text-mocha":"bg-taupe/10 text-taupe"}`}>{m.client_visible?"Visible en Access":"Interno"}</span></div>{m.summary&&<p className="mt-3 text-[12px] leading-relaxed text-taupe">{m.summary}</p>}<p className="mt-4 text-[9px] text-taupe">Actualizado {new Date(m.updated_at).toLocaleDateString("es-US")}</p></article>)}</div>}</div>)}</div></section>}
  {tab==="beauty_intelligence"&&<section className="mt-7"><div className="flex items-center gap-3 text-mocha"><Sparkles size={20}/><p className="text-[9px] uppercase tracking-[0.22em]">Inteligencia de Belleza</p></div><h2 className="mt-2 font-serif text-[35px] leading-none">Sugerencias con aprobación humana.</h2>{recs.length===0?<p className="mt-5 text-[12px] text-taupe">Todavía no hay recomendaciones. El sistema solo mostrará sugerencias reales, basadas en datos.</p>:<div className="mt-5 grid gap-4 md:grid-cols-2">{recs.map(r=><article key={r.id} className="rounded-[24px] border border-champagne/30 bg-white/45 p-6"><div className="flex items-center justify-between gap-3"><p className="text-[9px] uppercase tracking-[0.18em] text-mocha">{r.type.replace(/_/g," ")}</p><Badge>{statusLabels[r.status]||r.status}</Badge></div><h3 className="mt-3 font-serif text-[29px] leading-none">{r.title}</h3>{r.description&&<p className="mt-3 text-[12px] text-taupe">{r.description}</p>}{r.reason&&<p className="mt-4 text-[11px] italic text-taupe">Por qué: {r.reason}</p>}<div className="mt-5 flex gap-2"><button onClick={()=>publishRecommendation(r)} className="inline-flex items-center gap-1 rounded-full bg-espresso px-4 py-2 text-[8px] uppercase tracking-[.12em] text-ivory"><Check size={13}/>Publicar en Access</button><button onClick={()=>dismissRecommendation(r)} className="rounded-full border border-mocha/25 px-4 py-2 text-[8px] uppercase tracking-[.12em] text-mocha">Descartar</button></div></article>)}</div>}</section>}
  {!(["overview","client_memory","beauty_intelligence"] as string[]).includes(tab)&&<section className="mt-7 rounded-[24px] border border-champagne/30 bg-white/45 p-7"><h2 className="font-serif text-[31px]">{tabLabels[tab]}</h2><p className="mt-3 text-[12px] text-taupe">Esta pestaña está conectada al perfil compartido de la clienta y se completará junto con el resto de los módulos del Hub.</p></section>}
  </div>
}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full bg-blush px-3 py-1.5 text-[8px] uppercase tracking-[0.12em] text-mocha">{children}</span>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-[22px] border border-champagne/30 bg-white/45 p-5"><p className="text-[8px] uppercase tracking-[.18em] text-taupe">{label}</p><p className="mt-3 font-serif text-[28px] capitalize">{value}</p></div>}
function Select({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[]}){return <select value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-taupe/25 bg-ivory/70 px-4 py-3 text-[12px]">{options.map(o=><option key={o} value={o}>{categoryLabels[o]||o}</option>)}</select>}
