"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowRight, CalendarDays, ChevronRight, Droplets, Heart, Mail, Phone, ShoppingBag, Sparkles, UserRound } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Client={id:string;first_name:string;last_name:string;email:string|null;phone:string|null;access_status:string;beauty_state:string;created_at:string};
type Memory={id:string;category:string;title:string;summary:string|null;details:Record<string,unknown>;products_used:unknown;maintenance_notes:string|null;client_visible:boolean;updated_at:string;appointment_id:string|null;service_id:string|null;staff_id:string|null};
type Appt={id:string;start_at:string;status:string;service:{name:string}|null;staff:{name:string}|null};
type Metrics={segment:string;completed_visits:number;last_visit:string|null;days_since_last_visit:number|null};
type Tab="overview"|"beauty"|"appointments"|"products"|"activity";

const familyMeta:Record<string,{label:string;eyebrow:string}>={
  color:{label:"Hair Color",eyebrow:"Color + formula"},blowdry:{label:"Blowdry",eyebrow:"Her signature finish"},cut:{label:"Cut",eyebrow:"Shape + length"},treatment:{label:"Treatments",eyebrow:"Hair health"},styling:{label:"Styling",eyebrow:"Looks worth repeating"},extensions:{label:"Extensions",eyebrow:"Length + color match"},nails:{label:"Nails",eyebrow:"Shape + shade"},lashes:{label:"Lashes",eyebrow:"Map + curl"},brows:{label:"Brows",eyebrow:"Shape + tint"},makeup:{label:"Makeup",eyebrow:"Her best tones"},tanning:{label:"Glow",eyebrow:"Her perfect tone"},hair:{label:"Hair",eyebrow:"Hair memory"},general:{label:"Beauty Notes",eyebrow:"Personal details"}
};
const tabLabels:Record<Tab,string>={overview:"Resumen",beauty:"My Beauty Profile",appointments:"Citas",products:"Productos",activity:"Actividad"};

export default function HubClientDetail(){
  const params=useParams<{id:string}>();const id=params.id;
  const [client,setClient]=useState<Client|null>(null);const [memory,setMemory]=useState<Memory[]>([]);const [appointments,setAppointments]=useState<Appt[]>([]);const [metrics,setMetrics]=useState<Metrics|null>(null);const [tab,setTab]=useState<Tab>("overview");
  useEffect(()=>{if(!id)return;(async()=>{const [{data:c},{data:m},{data:a},{data:v}]=await Promise.all([
    supabase.from("client_profiles").select("id,first_name,last_name,email,phone,access_status,beauty_state,created_at").eq("id",id).single(),
    supabase.from("client_memory").select("id,category,title,summary,details,products_used,maintenance_notes,client_visible,updated_at,appointment_id,service_id,staff_id").eq("client_id",id).order("updated_at",{ascending:false}),
    supabase.from("appointments").select("id,start_at,status,service:service_id(name),staff:staff_id(name)").eq("client_id",id).order("start_at",{ascending:false}).limit(30),
    supabase.from("client_value_metrics").select("segment,completed_visits,last_visit,days_since_last_visit").eq("client_id",id).maybeSingle(),
  ]);setClient(c as Client);setMemory((m as Memory[])||[]);setAppointments(((a as unknown) as Appt[])||[]);setMetrics((v as Metrics|null)||null)})()},[id]);
  const families=useMemo(()=>{const map=new Map<string,Memory[]>();memory.forEach(m=>{const family=String(m.details?.service_family||m.category||"general");if(!map.has(family))map.set(family,[]);map.get(family)!.push(m)});return [...map.entries()]},[memory]);
  const latest=appointments[0]||null;const upcoming=appointments.find(a=>["pending","confirmed","in_progress"].includes(a.status)&&new Date(a.start_at)>=new Date())||null;
  if(!client)return <p className="text-[12px] text-taupe">Cargando clienta…</p>;

  return <div className="pb-10">
    <section className="overflow-hidden rounded-[28px] bg-[#34261F] text-ivory shadow-[0_18px_50px_rgba(52,38,31,.12)]">
      <div className="grid gap-6 p-6 md:p-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[9px] uppercase tracking-[.28em] text-champagne">Client Beauty Passport</p><h1 className="mt-2 font-serif text-[44px] md:text-[58px] leading-none">{client.first_name} {client.last_name}</h1><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-[11px] text-ivory/65">{client.phone&&<span className="inline-flex items-center gap-1.5"><Phone size={13}/>{client.phone}</span>}{client.email&&<span className="inline-flex items-center gap-1.5"><Mail size={13}/>{client.email}</span>}</div></div><div className="grid grid-cols-2 gap-2 sm:flex"><MiniStat label="Visitas" value={String(metrics?.completed_visits||0)}/><MiniStat label="Status" value={segment(metrics?.segment)}/></div></div>
      <div className="border-t border-white/10 bg-white/[.04] px-6 py-4 md:px-8"><p className="font-serif italic text-[17px] text-champagne">“La próxima visita empieza recordando la anterior.”</p></div>
    </section>

    <div className="mt-5 flex gap-2 overflow-x-auto pb-1">{(Object.keys(tabLabels) as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 rounded-full px-4 py-2.5 text-[10px] ${tab===t?"bg-[#4A352B] text-ivory":"border border-champagne/35 bg-white/60 text-taupe"}`}>{tabLabels[t]}</button>)}</div>

    {tab==="overview"&&<div className="mt-6 grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-[24px] border border-champagne/30 bg-white/75 p-5 md:p-6"><p className="text-[9px] uppercase tracking-[.22em] text-mocha">Beauty at a glance</p><h2 className="mt-2 font-serif text-[34px]">Lo que ya sabemos de ella</h2>{families.length?<div className="mt-5 grid gap-3 sm:grid-cols-2">{families.slice(0,6).map(([family,items])=><button key={family} onClick={()=>setTab("beauty")} className="group rounded-[18px] border border-champagne/25 bg-[#FBF8F3] p-4 text-left"><p className="text-[8px] uppercase tracking-[.18em] text-mocha">{familyMeta[family]?.eyebrow||"Beauty memory"}</p><div className="mt-2 flex items-end justify-between gap-3"><div><p className="font-serif text-[24px] leading-none">{familyMeta[family]?.label||human(family)}</p><p className="mt-2 text-[11px] text-taupe line-clamp-1">{items[0].title}</p></div><ChevronRight size={16} className="text-mocha transition-transform group-hover:translate-x-1"/></div></button>)}</div>:<Empty text="Su Beauty Profile se irá formando cuando el team complete sus visitas."/>}</section><div className="space-y-4"><InfoCard icon={CalendarDays} eyebrow={upcoming?"Próxima cita":"Agenda"} title={upcoming?upcoming.service?.name||"Appointment":"Sin próxima cita"} text={upcoming?`${date(upcoming.start_at)} · ${upcoming.staff?.name||"Team"}`:"Puedes reservarle una cita desde Calendar."} href="/hub/calendar" action={upcoming?"Ver calendario":"Crear cita"}/><InfoCard icon={Sparkles} eyebrow="Última visita" title={latest?.service?.name||"Sin historial"} text={latest?`${date(latest.start_at)} · ${latest.staff?.name||"Team"}`:"Todavía no hay visitas registradas."}/></div></div>}

    {tab==="beauty"&&<section className="mt-6"><div className="max-w-[720px]"><p className="text-[9px] uppercase tracking-[.22em] text-mocha">My Beauty Profile</p><h2 className="mt-2 font-serif text-[40px] leading-none">Todo lo que hace que su servicio sea realmente suyo.</h2><p className="mt-3 text-[12px] leading-relaxed text-taupe">Aquí solo aparecen categorías que el equipo ya trabajó. Cada nueva visita puede actualizar color, fórmula, acabado, shape, pestañas, cejas, extensiones y productos reales usados.</p></div>{families.length?<div className="mt-6 grid gap-4 xl:grid-cols-2">{families.map(([family,items])=><BeautySection key={family} family={family} items={items}/>)}</div>:<Empty text="Todavía no hay detalles guardados. Se crearán desde Guardar + Completar al finalizar una cita."/>}</section>}

    {tab==="appointments"&&<section className="mt-6 rounded-[24px] border border-champagne/30 bg-white/70 p-5 md:p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.2em] text-mocha">Historial</p><h2 className="mt-1 font-serif text-[32px]">Citas</h2></div><Link href="/hub/calendar?new=1" className="rounded-full bg-[#4A352B] px-4 py-2.5 text-[9px] text-ivory">+ Nueva cita</Link></div><div className="mt-5 divide-y divide-champagne/20">{appointments.length?appointments.map(a=><div key={a.id} className="flex items-center gap-4 py-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-blush/45 text-mocha"><CalendarDays size={17}/></div><div className="min-w-0 flex-1"><p className="font-serif text-[21px] truncate">{a.service?.name||"Appointment"}</p><p className="mt-1 text-[10px] text-taupe">{date(a.start_at)} · {a.staff?.name||"Team"}</p></div><span className="text-[9px] text-taupe">{human(a.status)}</span></div>):<Empty text="Sin citas todavía."/>}</div></section>}

    {tab==="products"&&<section className="mt-6"><p className="text-[9px] uppercase tracking-[.22em] text-mocha">Products used on her</p><h2 className="mt-2 font-serif text-[38px]">Su rutina real</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{uniqueProducts(memory).length?uniqueProducts(memory).map((p,i)=><div key={`${p.type}-${p.name}-${i}`} className="rounded-[20px] border border-champagne/30 bg-white/70 p-5"><ShoppingBag size={17} className="text-mocha"/><p className="mt-4 text-[8px] uppercase tracking-[.18em] text-taupe">{human(p.type)}</p><p className="mt-1 font-serif text-[24px]">{p.name}</p></div>):<Empty text="Todavía no hay productos registrados para ella."/>}</div></section>}

    {tab==="activity"&&<section className="mt-6 rounded-[24px] border border-champagne/30 bg-white/70 p-6"><p className="text-[9px] uppercase tracking-[.2em] text-mocha">Activity</p><h2 className="mt-2 font-serif text-[34px]">Beauty memory timeline</h2><div className="mt-5 space-y-4">{memory.map(m=><div key={m.id} className="flex gap-4"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-mocha"/><div><p className="font-serif text-[20px]">{m.title}</p><p className="mt-1 text-[10px] text-taupe">{date(m.updated_at)} · {familyMeta[String(m.details?.service_family||m.category)]?.label||human(m.category)}</p></div></div>)}</div></section>}
  </div>
}

function BeautySection({family,items}:{family:string;items:Memory[]}){const m=items[0];const details=Object.entries(m.details||{}).filter(([k,v])=>k!=="service_family"&&v!==null&&v!=="");return <article className="overflow-hidden rounded-[24px] border border-champagne/30 bg-white/75 shadow-[0_8px_30px_rgba(52,38,31,.04)]"><div className="bg-[#EFE4DC]/55 p-5"><p className="text-[8px] uppercase tracking-[.2em] text-mocha">{familyMeta[family]?.eyebrow||"Beauty memory"}</p><div className="mt-1 flex items-end justify-between gap-3"><h3 className="font-serif text-[32px] leading-none">{familyMeta[family]?.label||human(family)}</h3><span className="text-[9px] text-taupe">Actualizado {shortDate(m.updated_at)}</span></div>{m.summary&&<p className="mt-3 text-[12px] leading-relaxed text-taupe">{m.summary}</p>}</div><div className="p-5"><dl className="grid grid-cols-2 gap-x-5 gap-y-4">{details.slice(0,10).map(([k,v])=><div key={k}><dt className="text-[8px] uppercase tracking-[.14em] text-taupe">{human(k)}</dt><dd className="mt-1 text-[12px] font-medium">{formatValue(v)}</dd></div>)}</dl>{m.maintenance_notes&&<div className="mt-5 rounded-[16px] bg-[#FBF8F3] p-4"><p className="text-[8px] uppercase tracking-[.16em] text-mocha">Mantenimiento</p><p className="mt-2 text-[11px] leading-relaxed text-taupe">{m.maintenance_notes}</p></div>}{items.length>1&&<p className="mt-4 text-[9px] text-taupe">+ {items.length-1} visitas anteriores guardadas</p>}</div></article>}
function InfoCard({icon:Icon,eyebrow,title,text,href,action}:{icon:any;eyebrow:string;title:string;text:string;href?:string;action?:string}){return <div className="rounded-[24px] border border-champagne/30 bg-white/75 p-5"><Icon size={18} className="text-mocha"/><p className="mt-4 text-[8px] uppercase tracking-[.18em] text-taupe">{eyebrow}</p><p className="mt-1 font-serif text-[27px] leading-none">{title}</p><p className="mt-3 text-[11px] leading-relaxed text-taupe">{text}</p>{href&&<Link href={href} className="mt-4 inline-flex items-center gap-1.5 text-[9px] uppercase tracking-[.13em] text-mocha">{action}<ArrowRight size={14}/></Link>}</div>}
function MiniStat({label,value}:{label:string;value:string}){return <div className="min-w-[110px] rounded-[16px] border border-white/12 bg-white/[.06] px-4 py-3"><p className="text-[8px] uppercase tracking-[.17em] text-ivory/45">{label}</p><p className="mt-1 font-serif text-[21px] capitalize text-champagne">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="mt-5 rounded-[18px] border border-dashed border-champagne/40 bg-[#FBF8F3] p-5 text-[11px] text-taupe">{text}</div>}
function uniqueProducts(memory:Memory[]){const out:{type:string;name:string}[]=[];const seen=new Set<string>();memory.forEach(m=>{const raw=m.products_used;if(Array.isArray(raw))raw.forEach((x:any)=>{const type=typeof x==="object"?String(x.type||"product"):"product";const name=typeof x==="object"?String(x.name||""):String(x||"");const key=`${type}|${name}`.toLowerCase();if(name&&!seen.has(key)){seen.add(key);out.push({type,name})}})});return out}
function segment(v?:string){if(!v)return "Nueva";return ({new:"Nueva",regular:"Regular",loyal:"Fiel",vip:"VIP",at_risk:"En riesgo"} as Record<string,string>)[v]||human(v)}
function human(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function date(v:string){return new Date(v).toLocaleDateString("es-US",{month:"short",day:"numeric",year:"numeric",timeZone:"America/New_York"})}
function shortDate(v:string){return new Date(v).toLocaleDateString("es-US",{month:"short",day:"numeric",timeZone:"America/New_York"})}
function formatValue(v:unknown){if(Array.isArray(v))return v.join(", ");if(typeof v==="boolean")return v?"Sí":"No";if(v===null||v===undefined)return "—";return String(v)}
