"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { Check, Plus, Sparkles } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Client={id:string;first_name:string;last_name:string;email:string|null;phone:string|null;access_status:string;beauty_state:string;created_at:string};
type Memory={id:string;category:string;title:string;summary:string|null;details:Record<string,unknown>;client_visible:boolean;visibility:string;updated_at:string};
type Recommendation={id:string;type:string;category:string;title:string;description:string|null;reason:string|null;status:string;client_visible:boolean};
type Metrics={segment:string;lifetime_spend:number;average_ticket:number;completed_visits:number;last_visit:string|null;days_since_last_visit:number|null};
const categories=["hair","nails","brows","lashes","tanning","makeup"];

export default function HubClientDetail(){
  const params=useParams<{id:string}>(); const id=params.id;
  const [client,setClient]=useState<Client|null>(null); const [memory,setMemory]=useState<Memory[]>([]); const [recs,setRecs]=useState<Recommendation[]>([]); const [metrics,setMetrics]=useState<Metrics|null>(null); const [tab,setTab]=useState("overview"); const [open,setOpen]=useState(false); const [form,setForm]=useState({category:"hair",title:"",summary:"",visibility:"internal"});
  async function load(){const [{data:c},{data:m},{data:r},{data:v}]=await Promise.all([supabase.from("client_profiles").select("id,first_name,last_name,email,phone,access_status,beauty_state,created_at").eq("id",id).single(),supabase.from("client_memory").select("id,category,title,summary,details,client_visible,visibility,updated_at").eq("client_id",id).order("updated_at",{ascending:false}),supabase.from("beauty_recommendations").select("id,type,category,title,description,reason,status,client_visible").eq("client_id",id).order("created_at",{ascending:false}),supabase.from("client_value_metrics").select("segment,lifetime_spend,average_ticket,completed_visits,last_visit,days_since_last_visit").eq("client_id",id).maybeSingle()]);setClient(c as Client);setMemory((m as Memory[])||[]);setRecs((r as Recommendation[])||[]);setMetrics((v as Metrics|null)||null)}
  useEffect(()=>{if(id)load()},[id]);
  const grouped=useMemo(()=>categories.map(category=>[category,memory.filter(m=>m.category===category)] as const),[memory]);
  async function addMemory(e:FormEvent){e.preventDefault();const visible=form.visibility==="client_visible";const {error}=await supabase.from("client_memory").insert({client_id:id,category:form.category,title:form.title,summary:form.summary||null,details:{},client_visible:visible,visibility:form.visibility});if(!error){setOpen(false);setForm({category:"hair",title:"",summary:"",visibility:"internal"});load()}}
  async function publishRecommendation(rec:Recommendation){await supabase.from("beauty_recommendations").update({status:"published",client_visible:true}).eq("id",rec.id);load()}
  async function dismissRecommendation(rec:Recommendation){await supabase.from("beauty_recommendations").update({status:"dismissed",client_visible:false}).eq("id",rec.id);load()}
  if(!client)return <p className="text-[12px] text-taupe">Loading client…</p>;
  const tabs=["overview","appointments","client memory","products","orders","beauty intelligence","activity"];
  return <div><div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6"><div><p className="text-[9px] uppercase tracking-[0.28em] text-mocha">Client Profile</p><h1 className="mt-2 font-serif text-[45px] md:text-[58px] leading-none">{client.first_name} {client.last_name}</h1><p className="mt-3 text-[12px] text-taupe">{client.email||"No email"} · {client.phone||"No phone"}</p></div><div className="flex flex-wrap gap-2"><Badge>{client.access_status}</Badge><Badge>{client.beauty_state}</Badge>{metrics&&<Badge>{metrics.segment}</Badge>}</div></div>
  <div className="mt-8 overflow-x-auto border-b border-champagne/25"><div className="flex min-w-max gap-6">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`pb-3 text-[9px] uppercase tracking-[0.17em] ${tab===t?"border-b border-mocha text-mocha":"text-taupe"}`}>{t}</button>)}</div></div>
  {tab==="overview"&&<div className="mt-7 grid gap-4 md:grid-cols-4"><Stat label="Client Segment" value={metrics?.segment||"Not calculated"}/><Stat label="Completed Visits" value={String(metrics?.completed_visits||0)}/><Stat label="Average Ticket" value={metrics?`$${Number(metrics.average_ticket||0).toFixed(0)}`:"—"}/><Stat label="Last Visit" value={metrics?.last_visit?new Date(metrics.last_visit).toLocaleDateString():"—"}/></div>}
  {tab==="client memory"&&<section className="mt-7"><div className="flex items-center justify-between gap-4"><div><p className="text-[9px] uppercase tracking-[0.22em] text-mocha">Client Memory</p><h2 className="mt-2 font-serif text-[35px] leading-none">Remember the client, not just the appointment.</h2></div><button onClick={()=>setOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-full bg-espresso px-5 py-3 text-[9px] uppercase tracking-[0.14em] text-ivory"><Plus size={15}/>Add memory</button></div>{open&&<form onSubmit={addMemory} className="mt-5 rounded-[24px] border border-champagne/30 bg-white/45 p-5 grid gap-4 md:grid-cols-4"><Select value={form.category} onChange={v=>setForm(f=>({...f,category:v}))} options={categories}/><input required value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="Memory title" className="rounded-xl border border-taupe/25 bg-ivory/70 px-4 py-3 text-[12px] outline-none"/><input value={form.summary} onChange={e=>setForm(f=>({...f,summary:e.target.value}))} placeholder="Short summary" className="rounded-xl border border-taupe/25 bg-ivory/70 px-4 py-3 text-[12px] outline-none"/><select value={form.visibility} onChange={e=>setForm(f=>({...f,visibility:e.target.value}))} className="rounded-xl border border-taupe/25 bg-ivory/70 px-4 py-3 text-[12px]"><option value="internal">Internal only</option><option value="client_visible">Visible in Access</option></select><button className="md:col-span-4 justify-self-start rounded-full bg-mocha px-5 py-3 text-[9px] uppercase tracking-[0.14em] text-ivory">Save memory</button></form>}<div className="mt-6 space-y-7">{grouped.map(([category,items])=><div key={category}><div className="flex items-center gap-3"><p className="text-[9px] uppercase tracking-[0.22em] text-mocha">{category} memory</p><span className="h-px flex-1 bg-champagne/25"/></div>{items.length===0?<p className="mt-3 text-[12px] text-taupe">No {category} memory yet.</p>:<div className="mt-3 grid gap-3 md:grid-cols-2">{items.map(m=><article key={m.id} className="rounded-[22px] border border-champagne/30 bg-white/45 p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-serif text-[27px] leading-none">{m.title}</h3><span className={`rounded-full px-2.5 py-1 text-[8px] uppercase tracking-[.1em] ${m.client_visible?"bg-blush text-mocha":"bg-taupe/10 text-taupe"}`}>{m.client_visible?"Access visible":"Internal"}</span></div>{m.summary&&<p className="mt-3 text-[12px] leading-relaxed text-taupe">{m.summary}</p>}<p className="mt-4 text-[9px] text-taupe">Updated {new Date(m.updated_at).toLocaleDateString()}</p></article>)}</div>}</div>)}</div></section>}
  {tab==="beauty intelligence"&&<section className="mt-7"><div className="flex items-center gap-3 text-mocha"><Sparkles size={20}/><p className="text-[9px] uppercase tracking-[0.22em]">Beauty Intelligence</p></div><h2 className="mt-2 font-serif text-[35px] leading-none">Suggestions with human approval.</h2>{recs.length===0?<p className="mt-5 text-[12px] text-taupe">No recommendations yet. The system will only show real, data-backed suggestions here.</p>:<div className="mt-5 grid gap-4 md:grid-cols-2">{recs.map(r=><article key={r.id} className="rounded-[24px] border border-champagne/30 bg-white/45 p-6"><div className="flex items-center justify-between gap-3"><p className="text-[9px] uppercase tracking-[0.18em] text-mocha">{r.type.replace(/_/g," ")}</p><Badge>{r.status}</Badge></div><h3 className="mt-3 font-serif text-[29px] leading-none">{r.title}</h3>{r.description&&<p className="mt-3 text-[12px] text-taupe">{r.description}</p>}{r.reason&&<p className="mt-4 text-[11px] italic text-taupe">Why: {r.reason}</p>}<div className="mt-5 flex gap-2"><button onClick={()=>publishRecommendation(r)} className="inline-flex items-center gap-1 rounded-full bg-espresso px-4 py-2 text-[8px] uppercase tracking-[.12em] text-ivory"><Check size={13}/>Publish to Access</button><button onClick={()=>dismissRecommendation(r)} className="rounded-full border border-mocha/25 px-4 py-2 text-[8px] uppercase tracking-[.12em] text-mocha">Dismiss</button></div></article>)}</div>}</section>}
  {!['overview','client memory','beauty intelligence'].includes(tab)&&<section className="mt-7 rounded-[24px] border border-champagne/30 bg-white/45 p-7"><h2 className="font-serif text-[31px]">{tab.replace(/\b\w/g,c=>c.toUpperCase())}</h2><p className="mt-3 text-[12px] text-taupe">This tab is connected to the shared client profile and will be completed with the rest of the Hub modules.</p></section>}
  </div>
}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full bg-blush px-3 py-1.5 text-[8px] uppercase tracking-[0.12em] text-mocha">{String(children).replace(/_/g," ")}</span>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-[22px] border border-champagne/30 bg-white/45 p-5"><p className="text-[8px] uppercase tracking-[.18em] text-taupe">{label}</p><p className="mt-3 font-serif text-[28px] capitalize">{value.replace(/_/g," ")}</p></div>}
function Select({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[]}){return <select value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-taupe/25 bg-ivory/70 px-4 py-3 text-[12px]">{options.map(o=><option key={o} value={o}>{o[0].toUpperCase()+o.slice(1)}</option>)}</select>}
