"use client";

import { useEffect, useState } from "react";
import { Check, Clock3, Mail, Phone, X } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Inquiry={id:string;client_name:string;client_phone:string;client_email:string|null;preferred_date:string|null;preferred_time:string|null;notes:string|null;status:string;created_at:string;service:{name:string}|null;staff:{name:string}|null};

export default function InquiriesPage(){
  const [items,setItems]=useState<Inquiry[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState<string|null>(null);
  async function load(){const {data}=await supabase.from("booking_inquiries").select("id,client_name,client_phone,client_email,preferred_date,preferred_time,notes,status,created_at,service:service_id(name),staff:staff_id(name)").order("created_at",{ascending:false});setItems(((data as unknown) as Inquiry[])||[]);setLoading(false)}
  useEffect(()=>{load()},[]);
  async function review(item:Inquiry,status:"approved"|"declined"){setMessage(null);const {error}=await supabase.rpc("review_booking_inquiry",{p_inquiry_id:item.id,p_status:status});if(error){setMessage(error.message);return;}try{const {data:{session}}=await supabase.auth.getSession();if(session&&item.client_email)await fetch("/api/send-inquiry-status",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({inquiryId:item.id})})}catch{}setMessage(status==="approved"?"Solicitud aprobada y clienta notificada.":"Solicitud rechazada.");await load()}
  return <div className="pb-10"><div><p className="text-[9px] uppercase tracking-[.22em] text-mocha">Gloria Hub · Requests</p><h1 className="mt-2 font-serif text-[46px] leading-none">Solicitudes de cita</h1><p className="mt-3 max-w-[650px] text-[11px] leading-relaxed text-taupe">Servicios que requieren revisión antes de confirmarse. La especialista correspondiente puede aprobarlos o rechazarlos.</p></div>{message&&<p className="mt-5 rounded-[14px] bg-blush/35 px-4 py-3 text-[11px] text-mocha">{message}</p>}{loading?<p className="mt-8 text-[12px] text-taupe">Cargando solicitudes…</p>:<div className="mt-6 grid gap-4">{items.map(i=><article key={i.id} className="rounded-[24px] border border-[#DDD0C6] bg-white/70 p-5 md:p-6"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-[8px] uppercase tracking-[.1em] ${i.status==="pending"?"bg-[#F2E3D7] text-mocha":i.status==="approved"?"bg-[#DFE8D9] text-[#4A6045]":"bg-[#EEE4E1] text-taupe"}`}>{i.status}</span><span className="text-[8px] uppercase tracking-[.12em] text-taupe">{new Date(i.created_at).toLocaleDateString("es-US")}</span></div><h2 className="mt-3 font-serif text-[28px]">{i.service?.name||"Servicio"}</h2><p className="mt-1 text-[12px] text-mocha">{i.client_name}{i.staff?.name?` · prefiere ${i.staff.name}`:" · primera disponible"}</p><div className="mt-3 flex flex-wrap gap-3 text-[10px] text-taupe"><span className="inline-flex items-center gap-1"><Phone size={12}/>{i.client_phone}</span>{i.client_email&&<span className="inline-flex items-center gap-1"><Mail size={12}/>{i.client_email}</span>}{i.preferred_date&&<span className="inline-flex items-center gap-1"><Clock3 size={12}/>{i.preferred_date}{i.preferred_time?` · ${i.preferred_time}`:""}</span>}</div>{i.notes&&<p className="mt-4 rounded-[14px] bg-[#F8F2EC] p-3 text-[10px] leading-relaxed text-taupe">{i.notes}</p>}</div>{i.status==="pending"&&<div className="flex gap-2 md:shrink-0"><button onClick={()=>review(i,"approved")} className="inline-flex items-center gap-2 rounded-full bg-[#6F3642] px-4 py-3 text-[8px] uppercase tracking-[.12em] text-white"><Check size={13}/>Aprobar</button><button onClick={()=>review(i,"declined")} className="inline-flex items-center gap-2 rounded-full border border-[#BFAEA1] px-4 py-3 text-[8px] uppercase tracking-[.12em] text-mocha"><X size={13}/>Rechazar</button></div>}</div></article>)}</div>}</div>
}
