"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { CalendarPlus, MapPin, MessageCircle } from "lucide-react";
import { supabase } from "@/lib/supabase/client";
import { useAccess } from "@/components/access/AccessShell";

type Appt={id:string;start_at:string;end_at:string;status:string;booking_duration:number|null;price_cents:number|null;cancellation_reason:string|null;service_id:string;staff_id:string;service:{name:string;price_label:string}|null;staff:{name:string}|null};
type Settings={cancellation_window_hours:number;rescheduling_window_hours:number;cancellation_policy_text:string|null};

export default function AppointmentDetailPage(){
  const {profile}=useAccess(); const params=useParams<{id:string}>(); const router=useRouter();
  const [appt,setAppt]=useState<Appt|null>(null); const [settings,setSettings]=useState<Settings|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState<string|null>(null);
  useEffect(()=>{if(!profile)return;(async()=>{const [{data:a},{data:s}]=await Promise.all([supabase.from("appointments").select("id,start_at,end_at,status,booking_duration,price_cents,cancellation_reason,service_id,staff_id,service:service_id(name,price_label),staff:staff_id(name)").eq("id",params.id).eq("client_id",profile.id).maybeSingle(),supabase.from("appointment_settings").select("cancellation_window_hours,rescheduling_window_hours,cancellation_policy_text").eq("id",true).maybeSingle()]);setAppt((a as Appt|null)||null);setSettings((s as Settings|null)||null);setLoading(false)})()},[profile?.id,params.id]);
  if(loading)return <p className="text-sm text-taupe">Loading appointment...</p>;
  if(!appt)return <div><h1 className="font-serif text-[42px]">Appointment not found.</h1><Link href="/access/appointments" className="mt-5 inline-flex text-[11px] uppercase tracking-[0.13em] text-mocha">Back to appointments</Link></div>;
  const upcoming=new Date(appt.start_at).getTime()>Date.now()&&["pending","confirmed"].includes(appt.status);
  const google=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(`${appt.service?.name||"Appointment"} · Gloria Beauty Salon`)}&dates=${range(appt.start_at,appt.end_at)}&location=${encodeURIComponent("1130 SW 8th St, Miami, FL 33130")}&details=${encodeURIComponent(`With ${appt.staff?.name||"Gloria Beauty Salon"} · +1 (305) 781-5456`)}`;
  async function cancel(){if(!window.confirm("¿Seguro que quieres cancelar esta cita?"))return;const reason=window.prompt("Motivo de cancelación (opcional)")||null;const {error}=await supabase.rpc("cancel_my_appointment",{p_appointment_id:appt.id,p_reason:reason});if(error){setMessage(error.message);return;}setAppt({...appt,status:"cancelled",cancellation_reason:reason});setMessage("Tu cita ha sido cancelada.")}
  return <div className="max-w-[760px]"><p className="text-[10px] uppercase tracking-[0.28em] text-mocha">Gloria Access</p><h1 className="mt-2 font-serif text-[44px] md:text-[56px] leading-none">Tu cita</h1><section className="mt-8 rounded-[30px] border border-champagne/30 bg-white/45 p-7 md:p-9"><p className="text-[9px] uppercase tracking-[0.2em] text-mocha">{human(appt.status)}</p><h2 className="mt-3 font-serif text-[38px] leading-none">{appt.service?.name||"Appointment"}</h2><div className="mt-6 grid gap-3 text-[13px]"><Row l="Professional" v={appt.staff?.name||"Gloria Beauty Salon"}/><Row l="Date" v={date(appt.start_at)}/><Row l="Time" v={`${time(appt.start_at)} – ${time(appt.end_at)}`}/><Row l="Duration" v={`${Math.round((+new Date(appt.end_at)-+new Date(appt.start_at))/60000)} min`}/><Row l="Price" v={appt.service?.price_label||"—"}/><Row l="Location" v="1130 SW 8th St, Miami, FL 33130"/></div>{message&&<p className="mt-5 text-[12px] text-mocha">{message}</p>}<div className="mt-7 flex flex-wrap gap-2">{upcoming&&<Link href={`/access/appointments/${appt.id}/reschedule`} className="rounded-full bg-espresso px-5 py-3 text-[9px] uppercase tracking-[0.14em] text-ivory">Reprogramar</Link>}{upcoming&&<button onClick={cancel} className="rounded-full border border-mocha/30 px-5 py-3 text-[9px] uppercase tracking-[0.14em] text-mocha">Cancelar</button>}<a href={google} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-mocha/30 px-5 py-3 text-[9px] uppercase tracking-[0.14em] text-mocha"><CalendarPlus size={14}/> Add to Calendar</a><a href="https://maps.google.com/?q=1130+SW+8th+St+Miami+FL+33130" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-mocha/30 px-5 py-3 text-[9px] uppercase tracking-[0.14em] text-mocha"><MapPin size={14}/> Directions</a><a href="https://wa.me/13057815456" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-mocha/30 px-5 py-3 text-[9px] uppercase tracking-[0.14em] text-mocha"><MessageCircle size={14}/> Contact salon</a></div></section>{settings&&<section className="mt-5 rounded-[22px] border border-champagne/25 bg-blush/20 p-5"><p className="text-[9px] uppercase tracking-[0.17em] text-mocha">Appointment policy</p><p className="mt-2 text-[11px] leading-relaxed text-taupe">{settings.cancellation_policy_text||`Cancellations and rescheduling are available up to ${settings.cancellation_window_hours} hours before your appointment.`}</p></section>}<Link href="/access/appointments" className="mt-7 inline-flex text-[10px] uppercase tracking-[0.14em] text-mocha">← Mis citas</Link></div>
}
function Row({l,v}:{l:string;v:string}){return <div className="flex justify-between gap-5 border-b border-champagne/20 pb-2"><span className="text-taupe">{l}</span><span className="text-right">{v}</span></div>}
function human(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function date(v:string){return new Date(v).toLocaleDateString("es-US",{weekday:"long",month:"long",day:"numeric",year:"numeric",timeZone:"America/New_York"})}
function time(v:string){return new Date(v).toLocaleTimeString("es-US",{hour:"numeric",minute:"2-digit",timeZone:"America/New_York"})}
function range(a:string,b:string){const f=(v:string)=>new Date(v).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");return `${f(a)}/${f(b)}`}
