"use client";

import { useEffect, useState } from "react";
import { Save, ShoppingBag } from "lucide-react";
import { supabase } from "@/lib/supabase/client";

type Product={id:string;name:string;brand:string;slug:string;active:boolean;tags:string[];price_cents:number|null;inventory_quantity:number;featured:boolean};
export default function ProductsPage(){
  const [items,setItems]=useState<Product[]>([]);const [message,setMessage]=useState<string|null>(null);
  async function load(){const {data}=await supabase.from("product_catalog").select("id,name,brand,slug,active,tags,price_cents,inventory_quantity,featured").order("brand").order("name");setItems((data as Product[])||[])}
  useEffect(()=>{load()},[]);
  function patch(id:string,changes:Partial<Product>){setItems(prev=>prev.map(x=>x.id===id?{...x,...changes}:x))}
  async function save(p:Product){setMessage(null);const {error}=await supabase.rpc("hub_update_product",{p_product_id:p.id,p_active:p.active,p_price_cents:p.price_cents||0,p_inventory:p.inventory_quantity,p_featured:p.featured});setMessage(error?error.message:`${p.name} guardado.`)}
  return <div><div className="flex items-end justify-between gap-5"><div><p className="text-[10px] uppercase tracking-[0.28em] text-mocha">Gloria Hub</p><h1 className="mt-2 font-serif text-[48px] md:text-[58px] leading-none">Productos</h1><p className="mt-3 text-[13px] text-taupe">Administra el catálogo activo de Gloria Shop, precios y stock.</p></div><ShoppingBag className="text-mocha"/></div>{message&&<p className="mt-4 text-[12px] text-mocha">{message}</p>}<div className="mt-8 overflow-hidden rounded-[22px] border border-champagne/30 bg-white/40">{items.length===0?<p className="p-7 text-[12px] text-taupe">Todavía no hay productos.</p>:items.map(p=><div key={p.id} className="grid gap-3 border-b last:border-0 border-champagne/20 p-4 md:grid-cols-[1.2fr_120px_110px_100px_100px_auto] md:items-center"><div><p className="text-[13px] font-medium">{p.name}</p><p className="mt-1 text-[10px] text-taupe">{p.brand} · {p.tags?.slice(0,3).join(" · ")}</p></div><label><span className="block text-[8px] uppercase tracking-[0.12em] text-taupe">Precio</span><input type="number" min={0} step="0.01" value={(p.price_cents||0)/100} onChange={e=>patch(p.id,{price_cents:Math.round(Number(e.target.value)*100)})} className="mt-1 w-full rounded-xl border border-taupe/25 bg-ivory px-3 py-2.5 text-[12px]"/></label><label><span className="block text-[8px] uppercase tracking-[0.12em] text-taupe">Stock</span><input type="number" min={0} value={p.inventory_quantity} onChange={e=>patch(p.id,{inventory_quantity:Number(e.target.value)})} className="mt-1 w-full rounded-xl border border-taupe/25 bg-ivory px-3 py-2.5 text-[12px]"/></label><label className="flex items-center gap-2 text-[11px] text-taupe"><input type="checkbox" checked={p.featured} onChange={e=>patch(p.id,{featured:e.target.checked})}/> Destacado</label><label className="flex items-center gap-2 text-[11px] text-taupe"><input type="checkbox" checked={p.active} onChange={e=>patch(p.id,{active:e.target.checked})}/> Activo</label><button onClick={()=>save(p)} className="inline-flex items-center justify-center gap-2 rounded-full bg-espresso px-4 py-2.5 text-[9px] uppercase tracking-[0.12em] text-ivory"><Save size={13}/>Guardar</button></div>)}</div></div>
}
